### ISSUE TITLE
Exception: Vertex buffers are write-only on OpenGL ES platforms

### ISSUE THREAD

**Issue by k4G17eYWI** [cpt-max/Docs#1]
Hi! I've tried to get data from compute buffer on my android device and got this:

```
android.runtime.JavaProxyThrowable: [System.NotSupportedException]: 
Microsoft.Xna.Framework.Graphics.BufferResource.PlatformGetData(Unknown Source:0)
Microsoft.Xna.Framework.Graphics.StructuredBuffer.GetData(Unknown Source:0)
Microsoft.Xna.Framework.Graphics.StructuredBuffer.GetData(Unknown Source:0)
MyStructuredBuffer.GetData(Unknown Source:0)
```

On a windows build everyting works well.
As far I know GL ES 3 supports getting data from buffer and this is just old xna code interfering.

**Comment by cpt-max** [comment]
Thanks for reporting. I'll have a look at it when I find some spare time.

**Comment by cpt-max** [comment]
fix is discussed here: https://github.com/cpt-max/MonoGame/pull/5
